### ISSUE TITLE
Support UART Air Quality Sensors

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Protobuf#119]
Related:
* https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/359

**Comment by brentru** [comment]
Q: Can we do 2x hardware UART (ie: AQ Monitor and GPS)

**Comment by tyeth** [comment]
I've got the Ikea vindriktning UART particle sensor https://esphome.io/components/sensor/pm1006.html https://learn.adafruit.com/ikea-vindriktning-hack-with-qt-py-esp32-s3-and-adafruit-io

Also Winsen UART CO2 sensor MH-Z19b, they have a few models with different ranges + interfaces and power requirements but all very similar https://www.winsen-sensor.com/sensors/co2-sensor/mh-z19b.html

Also some GPS things. An old NMEA stream over uart device for a car, and some SimCom GPS/GSM/3G/4G/5G modules with ESP32's attached to most (ignoring soldered on SimCom SOMS I have one that is a Pi Hat and some that are PCI-E based but designed for lilygo/ttgo T-PCI-E esp32 boards).

**Comment by brentru** [comment]
Supported in Beta 73 onwards, closing!
